services:
    - name: "service-1"
      addr: ":7777"
      handler:
          type: "socks5"
          auth:
              username: username
              password: password
      listener:
          type: "tcp"
