version: "3.8"

services:
    gost-socks5:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "${SOCKS5_EXTERNAL_PORT}:${SOCKS5_PORT}"
        networks:
            - gost-socks5-network

networks:
    gost-socks5-network:
