version: "3.8"

services:
    gost-tls:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "${TLS_EXTERNAL_PORT}:${TLS_PORT}"
        networks:
            - gost-tls-network

networks:
    gost-tls-network:
