services:
    - name: "service-0"
      addr: ":8443"
      handler:
          type: "http"
      listener:
          type: "tls"
          tls:
              certFile: "cert.pem"
              keyFile: "key.pem"
    - name: "service-1"
      addr: ":7777"
      handler:
          type: "socks5"
      listener:
          type: "tcp"
